
-- description generated by Pat driver

--			date     : Wed Jan 30 19:31:04 2019
--			revision : v109

--			sequence : pattern

-- input / output list :
in       a B;
in       b B;
in       c B;
in       d B;
out      output B;

begin

-- Pattern description :

--  abcd o 
--       u 
--       t 
--       p 
--       u 
--       t 


# resultat de fun_f
  : 0110?0;
  : 0111?0;

end;
